name: Pull Request

on:
  pull_request:
    branches:
    - master
    - next

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [14, 16]
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}
    - name: Install dependencies
      run: yarn
    - name: Build packages
      run: yarn compile
    - name: Run tests
      run: yarn test
    - name: Lint code
      run: yarn lint
    - name: Audit packages
      run: bash ./scripts/audit.sh
      shell: bash
